// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pffgfzslzvnvsbirkoxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmZmdmenNsenZudnNiaXJrb3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTA4OTQsImV4cCI6MjA2NTkyNjg5NH0.-t1DCW_qEybri80S1OI1CJQ8lRHLATKWX4HN_Wol19Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);