// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuebzjfcxrpeeokbzmca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1ZWJ6amZjeHJwZWVva2J6bWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMjA1MTUsImV4cCI6MjA1MDg5NjUxNX0.ipB8mXiJxEJOJoJ-QyFtQTZWntywzNUBxuR-cnYgZSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);